// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVrzjAezghx-BPxGKgDH0St2bl9BBOCWc',
    appId: '1:411347865609:web:839d1251d7c517c2a7a8d8',
    messagingSenderId: '411347865609',
    projectId: 'rhyno-f4427',
    authDomain: 'rhyno-f4427.firebaseapp.com',
    storageBucket: 'rhyno-f4427.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2CQYDVZiEJb5607J33JmDeN0QkmLj0PQ',
    appId: '1:411347865609:android:b705231b8dda43dda7a8d8',
    messagingSenderId: '411347865609',
    projectId: 'rhyno-f4427',
    storageBucket: 'rhyno-f4427.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjZ_RF9OJvBjIwgvIkkXv8CgbF3q4wGBM',
    appId: '1:411347865609:ios:f7cdd86f9505c1d0a7a8d8',
    messagingSenderId: '411347865609',
    projectId: 'rhyno-f4427',
    storageBucket: 'rhyno-f4427.appspot.com',
    iosClientId: '411347865609-fneredsf15inblve31e03leb8rmcn0b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.rhynoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjZ_RF9OJvBjIwgvIkkXv8CgbF3q4wGBM',
    appId: '1:411347865609:ios:f7cdd86f9505c1d0a7a8d8',
    messagingSenderId: '411347865609',
    projectId: 'rhyno-f4427',
    storageBucket: 'rhyno-f4427.appspot.com',
    iosClientId: '411347865609-fneredsf15inblve31e03leb8rmcn0b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.rhynoApp',
  );
}
